#!/bin/bash
echo Restarting geod...
killall -9 geod || true
chmod -R 755 /private/var/mobile/Library/Application\ Support/com.skyglow.mapsx/
chown mobile:mobile /private/var/mobile/Library/Application\ Support/com.skyglow.mapsx/
mkdir /private/var/mobile/Library/Application\ Support/com.skyglow.mapsx/  >/dev/null 2>&1 || true